"""empty message

Revision ID: 54fc65194869
Revises: c534fc2a0cbe
Create Date: 2025-11-12 00:27:55.880266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54fc65194869"
down_revision: Union[str, Sequence[str], None] = "c534fc2a0cbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_templates", "query")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_templates",
        sa.Column("query", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
