"""empty message

Revision ID: f06849620c14
Revises: 54fc65194869
Create Date: 2025-11-15 13:48:46.595280

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f06849620c14"
down_revision: Union[str, Sequence[str], None] = "54fc65194869"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
